# **DeBERTa**

In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1" # "0" o "1"

In [2]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

Using device: cuda


In [3]:
from utils import *

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, classification_report, confusion_matrix
from datasets import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
)

/home/n.emmolo/miniconda3/envs/env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-11-08 18:24:36.050305: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-11-08 18:24:36.109290: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-11-08 18:24:37.383351: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may 

In [4]:
# Ignore warnings for cleaner output
import warnings
warnings.filterwarnings("ignore")

In [5]:
# --------------------
# Build model function
# --------------------

def build_model(learning_rate=2e-5, weight_decay=0.1):
    """
    Builds a RoBERTa model (roberta-base) for sequence classification.

    Args:
        learning_rate (float): Learning rate for the optimizer.
        weight_decay (float): Weight decay for AdamW optimizer.

    Returns:
        model (AutoModelForSequenceClassification): HuggingFace RoBERTa model.
        tokenizer (AutoTokenizer): Tokenizer associated with the model.
        train_args (TrainingArguments): Default training configuration.
    """

    model = AutoModelForSequenceClassification.from_pretrained("roberta-base", num_labels=2)
    tokenizer = AutoTokenizer.from_pretrained("roberta-base")

    train_args = TrainingArguments(
        output_dir="./roberta_finetune_output",
        eval_strategy="epoch",
        save_strategy="no",
        learning_rate=learning_rate,
        weight_decay=weight_decay,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        num_train_epochs=3,
        logging_dir="./logs",
        load_best_model_at_end=False,
        logging_steps=50,
        seed=42,
    )

    return model, tokenizer, train_args

In [6]:
# ----------------------
# Tokenization functions
# ----------------------

def tokenize_function(examples, tokenizer, max_len=128):
    """
    Tokenizes the input examples using the provided tokenizer.

    Args:
        examples (dict): A dictionary containing the text data to be tokenized.
        tokenizer (AutoTokenizer): The tokenizer to use for tokenization.
        max_len (int): Maximum length for padding/truncation.

    Returns:
        dict: Tokenized inputs with padding and truncation applied.
    """

    return tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=max_len,
    )


def tokenize_datasets(datasets, tokenizer):
    """
    Tokenizes multiple datasets using the provided tokenizer.

    Args:
        datasets (dict): A dictionary where keys are dataset names and values are dictionaries with 'train', 'val', and 'test' splits.
        tokenizer (AutoTokenizer): The tokenizer to use for tokenization.

    Returns:
        dict: A dictionary with the same keys as input datasets, but with tokenized datasets.
    """

    tokenized_datasets = {}
    
    for name, data in datasets.items():
        print(f"\n=== Tokenizing dataset: {name} ===")

        train_dataset = Dataset.from_dict({"text": data["train"][0], "label": data["train"][1].astype(int)})
        val_dataset = Dataset.from_dict({"text": data["val"][0], "label": data["val"][1].astype(int)})
        test_dataset = Dataset.from_dict({"text": data["test"][0], "label": data["test"][1].astype(int)})

        train_tokenized = train_dataset.map(lambda x: tokenize_function(x, tokenizer), batched=True)
        val_tokenized = val_dataset.map(lambda x: tokenize_function(x, tokenizer), batched=True)
        test_tokenized = test_dataset.map(lambda x: tokenize_function(x, tokenizer), batched=True)

        tokenized_datasets[name] = {
            "train": (train_tokenized, np.array(train_dataset["label"])),
            "val": (val_tokenized, np.array(val_dataset["label"])),
            "test": (test_tokenized, np.array(test_dataset["label"]))
        }

    return tokenized_datasets

## VERSION 1: Dataset (Simple)

In [7]:
dataset_df = data_loading() # load all datasets

for name, df in dataset_df.items():
    print(f"Name: {name}, Number of samples: {len(df)}")

# dataset_df = dict(list(dataset_df.items())[:5])

print("\nSplitting datasets into train/val/test...")
datasets = {name: split_dataset(df) for name, df in dataset_df.items()} # split all datasets in train/val/test

model, tokenizer, train_args = build_model()

print("\nComputing tokenized datasets...")
datasets =  tokenize_datasets(datasets, tokenizer) # tokenize all datasets

Name: Celebrity, Number of samples: 500
Name: CIDII, Number of samples: 722
Name: FaKES, Number of samples: 842
Name: FakeVsSatire, Number of samples: 486
Name: Horne, Number of samples: 326
Name: Infodemic, Number of samples: 10559
Name: ISOT, Number of samples: 44271
Name: Kaggle_clement, Number of samples: 39105
Name: Kaggle_meg, Number of samples: 12845
Name: LIAR_PLUS, Number of samples: 12784
Name: Politifact, Number of samples: 504
Name: Unipi_NDF, Number of samples: 554

Splitting datasets into train/val/test...


Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.



Computing tokenized datasets...

=== Tokenizing dataset: Celebrity ===


Map: 100%|███████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 1848.57 examples/s]



=== Tokenizing dataset: CIDII ===


Map: 100%|███████████████████████████████████████████████████████████████| 145/145 [00:00<00:00, 3354.76 examples/s]



=== Tokenizing dataset: FaKES ===


Map: 100%|███████████████████████████████████████████████████████████████| 169/169 [00:00<00:00, 3228.92 examples/s]



=== Tokenizing dataset: FakeVsSatire ===


Map: 100%|█████████████████████████████████████████████████████████████████| 98/98 [00:00<00:00, 1761.51 examples/s]



=== Tokenizing dataset: Horne ===


Map: 100%|██████████████████████████████████████████████████████████████████| 66/66 [00:00<00:00, 976.21 examples/s]



=== Tokenizing dataset: Infodemic ===


Map: 100%|████████████████████████████████████████████████████████████| 2112/2112 [00:00<00:00, 12653.68 examples/s]



=== Tokenizing dataset: ISOT ===


Map: 100%|█████████████████████████████████████████████████████████████| 8855/8855 [00:02<00:00, 3263.92 examples/s]



=== Tokenizing dataset: Kaggle_clement ===


Map: 100%|█████████████████████████████████████████████████████████████| 7821/7821 [00:02<00:00, 3305.98 examples/s]



=== Tokenizing dataset: Kaggle_meg ===


Map: 100%|█████████████████████████████████████████████████████████████| 2569/2569 [00:01<00:00, 1844.97 examples/s]



=== Tokenizing dataset: LIAR_PLUS ===


Map: 100%|████████████████████████████████████████████████████████████| 2557/2557 [00:00<00:00, 14549.47 examples/s]



=== Tokenizing dataset: Politifact ===


Map: 100%|████████████████████████████████████████████████████████████████| 101/101 [00:00<00:00, 923.90 examples/s]



=== Tokenizing dataset: Unipi_NDF ===


Map: 100%|███████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 4533.85 examples/s]


In [8]:
# --------------------------------
# Fine-tuning on multiple datasets
# --------------------------------

results = {}

for i, (name, data) in enumerate(datasets.items()):
    print(f"\n=== Phase {i+1}: Fine-tuning on {name} ===")

    X_train, y_train = data["train"]
    X_val, y_val = data["val"]
    X_test, y_test = data["test"]

    # define trainer
    trainer = Trainer(
        model=model,
        args=train_args,
        train_dataset=X_train,
        eval_dataset=X_val,
    )

    # fine-tune on train + val
    trainer.train()

    # evaluate on current dataset
    y_pred = trainer.predict(X_test)
    y_pred = np.argmax(y_pred.predictions, axis=1)
    print(f"\nClassification Report after {name}:")
    print(classification_report(y_test, y_pred))
    print(f"Confusion Matrix after {name}:")
    print(confusion_matrix(y_test, y_pred))
    print(f"Weighted F1-score after {name}: {f1_score(y_test, y_pred, average='weighted'):.4f}")

    # evaluate on all datasets
    print("\n--- Evaluation on all datasets ---")
    results[name] = {}
    for test_name, test_data in datasets.items():
        X_te, y_te = test_data["test"]
        preds = trainer.predict(X_te)
        preds = np.argmax(preds.predictions, axis=1)
        f1 = f1_score(y_te, preds, average="weighted")
        results[name][test_name] = f1
        print(f"Evaluation on {test_name}: Weighted F1 = {f1:.4f}")



=== Phase 1: Fine-tuning on Celebrity ===


Epoch,Training Loss,Validation Loss
1,No log,0.585378
2,0.642400,0.476600
3,0.371200,0.517176



Classification Report after Celebrity:
              precision    recall  f1-score   support

           0       0.82      0.80      0.81        50
           1       0.80      0.82      0.81        50

    accuracy                           0.81       100
   macro avg       0.81      0.81      0.81       100
weighted avg       0.81      0.81      0.81       100

Confusion Matrix after Celebrity:
[[40 10]
 [ 9 41]]
Weighted F1-score after Celebrity: 0.8100

--- Evaluation on all datasets ---


Evaluation on Celebrity: Weighted F1 = 0.8100


Evaluation on CIDII: Weighted F1 = 0.5631


Evaluation on FaKES: Weighted F1 = 0.3779


Evaluation on FakeVsSatire: Weighted F1 = 0.6652


Evaluation on Horne: Weighted F1 = 0.5775


Evaluation on Infodemic: Weighted F1 = 0.4063


Evaluation on ISOT: Weighted F1 = 0.4362


Evaluation on Kaggle_clement: Weighted F1 = 0.7341


Evaluation on Kaggle_meg: Weighted F1 = 0.8868


Evaluation on LIAR_PLUS: Weighted F1 = 0.4176


Evaluation on Politifact: Weighted F1 = 0.5997


Evaluation on Unipi_NDF: Weighted F1 = 0.5417

=== Phase 2: Fine-tuning on CIDII ===


Epoch,Training Loss,Validation Loss
1,0.344400,0.178532
2,0.136500,0.278702
3,0.036200,0.222493



Classification Report after CIDII:
              precision    recall  f1-score   support

           0       0.98      0.99      0.98        85
           1       0.98      0.97      0.97        60

    accuracy                           0.98       145
   macro avg       0.98      0.98      0.98       145
weighted avg       0.98      0.98      0.98       145

Confusion Matrix after CIDII:
[[84  1]
 [ 2 58]]
Weighted F1-score after CIDII: 0.9793

--- Evaluation on all datasets ---


Evaluation on Celebrity: Weighted F1 = 0.5072


Evaluation on CIDII: Weighted F1 = 0.9793


Evaluation on FaKES: Weighted F1 = 0.3241


Evaluation on FakeVsSatire: Weighted F1 = 0.4452


Evaluation on Horne: Weighted F1 = 0.4099


Evaluation on Infodemic: Weighted F1 = 0.4067


Evaluation on ISOT: Weighted F1 = 0.8283


Evaluation on Kaggle_clement: Weighted F1 = 0.7792


Evaluation on Kaggle_meg: Weighted F1 = 0.0971


Evaluation on LIAR_PLUS: Weighted F1 = 0.3218


Evaluation on Politifact: Weighted F1 = 0.7091


Evaluation on Unipi_NDF: Weighted F1 = 0.2542

=== Phase 3: Fine-tuning on FaKES ===


Epoch,Training Loss,Validation Loss
1,0.792400,0.690791
2,0.702700,0.689301
3,0.686200,0.690850



Classification Report after FaKES:
              precision    recall  f1-score   support

           0       0.52      0.78      0.62        89
           1       0.46      0.21      0.29        80

    accuracy                           0.51       169
   macro avg       0.49      0.49      0.46       169
weighted avg       0.49      0.51      0.47       169

Confusion Matrix after FaKES:
[[69 20]
 [63 17]]
Weighted F1-score after FaKES: 0.4664

--- Evaluation on all datasets ---


Evaluation on Celebrity: Weighted F1 = 0.7494


Evaluation on CIDII: Weighted F1 = 0.8939


Evaluation on FaKES: Weighted F1 = 0.4664


Evaluation on FakeVsSatire: Weighted F1 = 0.6735


Evaluation on Horne: Weighted F1 = 0.6854


Evaluation on Infodemic: Weighted F1 = 0.7018


Evaluation on ISOT: Weighted F1 = 0.7384


Evaluation on Kaggle_clement: Weighted F1 = 0.9079


Evaluation on Kaggle_meg: Weighted F1 = 0.5643


Evaluation on LIAR_PLUS: Weighted F1 = 0.5729


Evaluation on Politifact: Weighted F1 = 0.7102


Evaluation on Unipi_NDF: Weighted F1 = 0.6028

=== Phase 4: Fine-tuning on FakeVsSatire ===


Epoch,Training Loss,Validation Loss
1,No log,0.501168
2,0.563600,0.546242
3,0.239700,0.604597



Classification Report after FakeVsSatire:
              precision    recall  f1-score   support

           0       0.83      0.71      0.76        41
           1       0.81      0.89      0.85        57

    accuracy                           0.82        98
   macro avg       0.82      0.80      0.81        98
weighted avg       0.82      0.82      0.81        98

Confusion Matrix after FakeVsSatire:
[[29 12]
 [ 6 51]]
Weighted F1-score after FakeVsSatire: 0.8137

--- Evaluation on all datasets ---


Evaluation on Celebrity: Weighted F1 = 0.7348


Evaluation on CIDII: Weighted F1 = 0.9377


Evaluation on FaKES: Weighted F1 = 0.5322


Evaluation on FakeVsSatire: Weighted F1 = 0.8137


Evaluation on Horne: Weighted F1 = 0.6382


Evaluation on Infodemic: Weighted F1 = 0.5084


Evaluation on ISOT: Weighted F1 = 0.7696


Evaluation on Kaggle_clement: Weighted F1 = 0.9831


Evaluation on Kaggle_meg: Weighted F1 = 0.4368


Evaluation on LIAR_PLUS: Weighted F1 = 0.4741


Evaluation on Politifact: Weighted F1 = 0.7199


Evaluation on Unipi_NDF: Weighted F1 = 0.5568

=== Phase 5: Fine-tuning on Horne ===


Epoch,Training Loss,Validation Loss
1,No log,0.467746
2,0.375600,0.509339
3,0.375600,0.565001



Classification Report after Horne:
              precision    recall  f1-score   support

           0       0.86      0.88      0.87        41
           1       0.79      0.76      0.78        25

    accuracy                           0.83        66
   macro avg       0.82      0.82      0.82        66
weighted avg       0.83      0.83      0.83        66

Confusion Matrix after Horne:
[[36  5]
 [ 6 19]]
Weighted F1-score after Horne: 0.8326

--- Evaluation on all datasets ---


Evaluation on Celebrity: Weighted F1 = 0.6480


Evaluation on CIDII: Weighted F1 = 0.9443


Evaluation on FaKES: Weighted F1 = 0.4737


Evaluation on FakeVsSatire: Weighted F1 = 0.7029


Evaluation on Horne: Weighted F1 = 0.8326


Evaluation on Infodemic: Weighted F1 = 0.4440


Evaluation on ISOT: Weighted F1 = 0.9422


Evaluation on Kaggle_clement: Weighted F1 = 0.9917


Evaluation on Kaggle_meg: Weighted F1 = 0.3805


Evaluation on LIAR_PLUS: Weighted F1 = 0.4615


Evaluation on Politifact: Weighted F1 = 0.8285


Evaluation on Unipi_NDF: Weighted F1 = 0.4344

=== Phase 6: Fine-tuning on Infodemic ===


Epoch,Training Loss,Validation Loss
1,0.167800,0.126454
2,0.147000,0.131944
3,0.021400,0.134417



Classification Report after Infodemic:
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      1106
           1       0.99      0.98      0.98      1006

    accuracy                           0.98      2112
   macro avg       0.98      0.98      0.98      2112
weighted avg       0.98      0.98      0.98      2112

Confusion Matrix after Infodemic:
[[1093   13]
 [  25  981]]
Weighted F1-score after Infodemic: 0.9820

--- Evaluation on all datasets ---


Evaluation on Celebrity: Weighted F1 = 0.3552


Evaluation on CIDII: Weighted F1 = 0.3400


Evaluation on FaKES: Weighted F1 = 0.3548


Evaluation on FakeVsSatire: Weighted F1 = 0.4278


Evaluation on Horne: Weighted F1 = 0.2081


Evaluation on Infodemic: Weighted F1 = 0.9820


Evaluation on ISOT: Weighted F1 = 0.4464


Evaluation on Kaggle_clement: Weighted F1 = 0.3974


Evaluation on Kaggle_meg: Weighted F1 = 0.0117


Evaluation on LIAR_PLUS: Weighted F1 = 0.2927


Evaluation on Politifact: Weighted F1 = 0.4627


Evaluation on Unipi_NDF: Weighted F1 = 0.4184

=== Phase 7: Fine-tuning on ISOT ===


Epoch,Training Loss,Validation Loss
1,0.000000,0.001770
2,0.000000,0.000001
3,0.000000,0.000001



Classification Report after ISOT:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4284
           1       1.00      1.00      1.00      4571

    accuracy                           1.00      8855
   macro avg       1.00      1.00      1.00      8855
weighted avg       1.00      1.00      1.00      8855

Confusion Matrix after ISOT:
[[4284    0]
 [   1 4570]]
Weighted F1-score after ISOT: 0.9999

--- Evaluation on all datasets ---


Evaluation on Celebrity: Weighted F1 = 0.3333


Evaluation on CIDII: Weighted F1 = 0.5459


Evaluation on FaKES: Weighted F1 = 0.3171


Evaluation on FakeVsSatire: Weighted F1 = 0.4203


Evaluation on Horne: Weighted F1 = 0.4759


Evaluation on Infodemic: Weighted F1 = 0.6598


Evaluation on ISOT: Weighted F1 = 0.9999


Evaluation on Kaggle_clement: Weighted F1 = 0.7082


Evaluation on Kaggle_meg: Weighted F1 = 0.0171


Evaluation on LIAR_PLUS: Weighted F1 = 0.2721


Evaluation on Politifact: Weighted F1 = 0.4925


Evaluation on Unipi_NDF: Weighted F1 = 0.3199

=== Phase 8: Fine-tuning on Kaggle_clement ===


Epoch,Training Loss,Validation Loss
1,0.029400,0.004319
2,0.000000,0.001522
3,0.000000,0.001812



Classification Report after Kaggle_clement:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4240
           1       1.00      1.00      1.00      3581

    accuracy                           1.00      7821
   macro avg       1.00      1.00      1.00      7821
weighted avg       1.00      1.00      1.00      7821

Confusion Matrix after Kaggle_clement:
[[4239    1]
 [   0 3581]]
Weighted F1-score after Kaggle_clement: 0.9999

--- Evaluation on all datasets ---


Evaluation on Celebrity: Weighted F1 = 0.3967


Evaluation on CIDII: Weighted F1 = 0.5781


Evaluation on FaKES: Weighted F1 = 0.5098


Evaluation on FakeVsSatire: Weighted F1 = 0.4723


Evaluation on Horne: Weighted F1 = 0.5892


Evaluation on Infodemic: Weighted F1 = 0.5353


Evaluation on ISOT: Weighted F1 = 0.9909


Evaluation on Kaggle_clement: Weighted F1 = 0.9999


Evaluation on Kaggle_meg: Weighted F1 = 0.1270


Evaluation on LIAR_PLUS: Weighted F1 = 0.5002


Evaluation on Politifact: Weighted F1 = 0.4471


Evaluation on Unipi_NDF: Weighted F1 = 0.4280

=== Phase 9: Fine-tuning on Kaggle_meg ===


Epoch,Training Loss,Validation Loss
1,0.071200,0.121434
2,0.110000,0.092530
3,0.133000,0.095409



Classification Report after Kaggle_meg:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      2514
           1       0.62      0.09      0.16        55

    accuracy                           0.98      2569
   macro avg       0.80      0.54      0.57      2569
weighted avg       0.97      0.98      0.97      2569

Confusion Matrix after Kaggle_meg:
[[2511    3]
 [  50    5]]
Weighted F1-score after Kaggle_meg: 0.9718

--- Evaluation on all datasets ---


Evaluation on Celebrity: Weighted F1 = 0.3333


Evaluation on CIDII: Weighted F1 = 0.4333


Evaluation on FaKES: Weighted F1 = 0.3633


Evaluation on FakeVsSatire: Weighted F1 = 0.2468


Evaluation on Horne: Weighted F1 = 0.4761


Evaluation on Infodemic: Weighted F1 = 0.3600


Evaluation on ISOT: Weighted F1 = 0.3056


Evaluation on Kaggle_clement: Weighted F1 = 0.3790


Evaluation on Kaggle_meg: Weighted F1 = 0.9718


Evaluation on LIAR_PLUS: Weighted F1 = 0.3993


Evaluation on Politifact: Weighted F1 = 0.5040


Evaluation on Unipi_NDF: Weighted F1 = 0.4654

=== Phase 10: Fine-tuning on LIAR_PLUS ===


Epoch,Training Loss,Validation Loss
1,0.694100,0.666152
2,0.629400,0.659776
3,0.603000,0.663869



Classification Report after LIAR_PLUS:
              precision    recall  f1-score   support

           0       0.65      0.76      0.70      1426
           1       0.61      0.48      0.53      1131

    accuracy                           0.63      2557
   macro avg       0.63      0.62      0.62      2557
weighted avg       0.63      0.63      0.63      2557

Confusion Matrix after LIAR_PLUS:
[[1078  348]
 [ 591  540]]
Weighted F1-score after LIAR_PLUS: 0.6251

--- Evaluation on all datasets ---


Evaluation on Celebrity: Weighted F1 = 0.3763


Evaluation on CIDII: Weighted F1 = 0.4050


Evaluation on FaKES: Weighted F1 = 0.4494


Evaluation on FakeVsSatire: Weighted F1 = 0.4609


Evaluation on Horne: Weighted F1 = 0.3965


Evaluation on Infodemic: Weighted F1 = 0.7316


Evaluation on ISOT: Weighted F1 = 0.2990


Evaluation on Kaggle_clement: Weighted F1 = 0.2921


Evaluation on Kaggle_meg: Weighted F1 = 0.4029


Evaluation on LIAR_PLUS: Weighted F1 = 0.6251


Evaluation on Politifact: Weighted F1 = 0.5496


Evaluation on Unipi_NDF: Weighted F1 = 0.4024

=== Phase 11: Fine-tuning on Politifact ===


Epoch,Training Loss,Validation Loss
1,No log,0.555828
2,0.615600,0.538644
3,0.432700,0.394333



Classification Report after Politifact:
              precision    recall  f1-score   support

           0       0.96      0.82      0.88        65
           1       0.74      0.94      0.83        36

    accuracy                           0.86       101
   macro avg       0.85      0.88      0.86       101
weighted avg       0.88      0.86      0.86       101

Confusion Matrix after Politifact:
[[53 12]
 [ 2 34]]
Weighted F1-score after Politifact: 0.8641

--- Evaluation on all datasets ---


Evaluation on Celebrity: Weighted F1 = 0.3711


Evaluation on CIDII: Weighted F1 = 0.3772


Evaluation on FaKES: Weighted F1 = 0.5078


Evaluation on FakeVsSatire: Weighted F1 = 0.5891


Evaluation on Horne: Weighted F1 = 0.5056


Evaluation on Infodemic: Weighted F1 = 0.8011


Evaluation on ISOT: Weighted F1 = 0.7727


Evaluation on Kaggle_clement: Weighted F1 = 0.8497


Evaluation on Kaggle_meg: Weighted F1 = 0.4890


Evaluation on LIAR_PLUS: Weighted F1 = 0.5930


Evaluation on Politifact: Weighted F1 = 0.8641


Evaluation on Unipi_NDF: Weighted F1 = 0.2855

=== Phase 12: Fine-tuning on Unipi_NDF ===


Epoch,Training Loss,Validation Loss
1,No log,0.658841
2,0.742100,0.381213
3,0.476600,0.326728



Classification Report after Unipi_NDF:
              precision    recall  f1-score   support

           0       0.90      0.97      0.94        68
           1       0.95      0.84      0.89        43

    accuracy                           0.92       111
   macro avg       0.93      0.90      0.91       111
weighted avg       0.92      0.92      0.92       111

Confusion Matrix after Unipi_NDF:
[[66  2]
 [ 7 36]]
Weighted F1-score after Unipi_NDF: 0.9179

--- Evaluation on all datasets ---


Evaluation on Celebrity: Weighted F1 = 0.6339


Evaluation on CIDII: Weighted F1 = 0.3489


Evaluation on FaKES: Weighted F1 = 0.4440


Evaluation on FakeVsSatire: Weighted F1 = 0.6129


Evaluation on Horne: Weighted F1 = 0.4920


Evaluation on Infodemic: Weighted F1 = 0.8173


Evaluation on ISOT: Weighted F1 = 0.7507


Evaluation on Kaggle_clement: Weighted F1 = 0.8059


Evaluation on Kaggle_meg: Weighted F1 = 0.4791


Evaluation on LIAR_PLUS: Weighted F1 = 0.5937


Evaluation on Politifact: Weighted F1 = 0.8228


Evaluation on Unipi_NDF: Weighted F1 = 0.9179


In [9]:
# ---------------
# Results summary
# ---------------

print("\n=== Results Summary ===")
for name, res in results.items():
    print(f"\nResults after training on {name}:")
    for test_name, f1 in res.items():
        print(f"  Test on {test_name}: Weighted F1 = {f1:.4f}")


=== Results Summary ===

Results after training on Celebrity:
  Test on Celebrity: Weighted F1 = 0.8100
  Test on CIDII: Weighted F1 = 0.5631
  Test on FaKES: Weighted F1 = 0.3779
  Test on FakeVsSatire: Weighted F1 = 0.6652
  Test on Horne: Weighted F1 = 0.5775
  Test on Infodemic: Weighted F1 = 0.4063
  Test on ISOT: Weighted F1 = 0.4362
  Test on Kaggle_clement: Weighted F1 = 0.7341
  Test on Kaggle_meg: Weighted F1 = 0.8868
  Test on LIAR_PLUS: Weighted F1 = 0.4176
  Test on Politifact: Weighted F1 = 0.5997
  Test on Unipi_NDF: Weighted F1 = 0.5417

Results after training on CIDII:
  Test on Celebrity: Weighted F1 = 0.5072
  Test on CIDII: Weighted F1 = 0.9793
  Test on FaKES: Weighted F1 = 0.3241
  Test on FakeVsSatire: Weighted F1 = 0.4452
  Test on Horne: Weighted F1 = 0.4099
  Test on Infodemic: Weighted F1 = 0.4067
  Test on ISOT: Weighted F1 = 0.8283
  Test on Kaggle_clement: Weighted F1 = 0.7792
  Test on Kaggle_meg: Weighted F1 = 0.0971
  Test on LIAR_PLUS: Weighted F1 = 0

## VERSION 2: Dataset by Topic

In [7]:
dataset_df = data_by_topic()

# split "politics" in "politics1" and "politics2"
if "politics" in dataset_df:
    dataset_df["politics1"] = dataset_df["politics"].sample(frac=0.5, random_state=42)
    dataset_df["politics2"] = dataset_df["politics"].drop(dataset_df["politics1"].index)
    # drop original "politics" dataset
    del dataset_df["politics"]
    # put "politics1" and "politics2" at the beginning of the dict
    dataset_df = {"politics1": dataset_df["politics1"], "politics2": dataset_df["politics2"], **dataset_df}

for topic, df in dataset_df.items():
    print(f"Topic: {topic}, Number of samples: {len(df)}")

# dataset_df = dict(list(dataset_df.items())[3:]) # remove first 3 datasets

print("\nSplitting datasets into train/val/test...")
datasets = {topic: split_dataset(df) for topic, df in dataset_df.items()} # split all datasets in train/val/test

model, tokenizer, train_args = build_model()

print("\nComputing tokenized datasets...")
datasets =  tokenize_datasets(datasets, tokenizer) # tokenize all datasets

Topic: politics1, Number of samples: 48738
Topic: politics2, Number of samples: 48738
Topic: general, Number of samples: 12845
Topic: covid, Number of samples: 10559
Topic: syria, Number of samples: 842
Topic: islam, Number of samples: 722
Topic: notredame, Number of samples: 554
Topic: gossip, Number of samples: 500

Splitting datasets into train/val/test...


Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.



Computing tokenized datasets...

=== Tokenizing dataset: politics1 ===


Map: 100%|█████████████████████████████████████████████████████████████| 9748/9748 [00:02<00:00, 3541.25 examples/s]



=== Tokenizing dataset: politics2 ===


Map: 100%|█████████████████████████████████████████████████████████████| 9748/9748 [00:02<00:00, 3549.86 examples/s]



=== Tokenizing dataset: general ===


Map: 100%|█████████████████████████████████████████████████████████████| 2569/2569 [00:01<00:00, 1845.37 examples/s]



=== Tokenizing dataset: covid ===


Map: 100%|████████████████████████████████████████████████████████████| 2112/2112 [00:00<00:00, 11920.19 examples/s]



=== Tokenizing dataset: syria ===


Map: 100%|███████████████████████████████████████████████████████████████| 169/169 [00:00<00:00, 3161.04 examples/s]



=== Tokenizing dataset: islam ===


Map: 100%|███████████████████████████████████████████████████████████████| 145/145 [00:00<00:00, 4011.76 examples/s]



=== Tokenizing dataset: notredame ===


Map: 100%|███████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 3877.89 examples/s]



=== Tokenizing dataset: gossip ===


Map: 100%|███████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 2193.77 examples/s]


In [8]:
# -------------------------------
# Fine-tuning on Dataset by Topic
# -------------------------------

results = {}

# sequential training
for i, (topic, data) in enumerate(datasets.items()):
    print(f"\n=== Phase {i+1}: Training/Fine-tuning on topic: {topic} ===")

    X_train, y_train = data["train"]
    X_val, y_val = data["val"]
    X_test, y_test = data["test"]

    # define trainer
    trainer = Trainer(
        model=model,
        args=train_args,
        train_dataset=X_train,
        eval_dataset=X_val,
    )

    # fine-tune on train + val
    trainer.train()

    # evaluate on current dataset
    y_pred = trainer.predict(X_test)
    y_pred = np.argmax(y_pred.predictions, axis=1)
    print(f"\nClassification Report after topic {topic}:")
    print(classification_report(y_test, y_pred))
    print(f"Confusion Matrix after topic {topic}:")
    print(confusion_matrix(y_test, y_pred))
    print(f"Weighted F1-score after topic {topic}:", f1_score(y_test, y_pred, average='weighted'))

    # evaluate on all datasets
    print("\n--- Evaluation on all datasets ---")
    results[topic] = {}
    for test_topic, test_data in datasets.items(): # for each topic
        X_te, y_te = test_data["test"]
        preds = trainer.predict(X_te)
        preds = np.argmax(preds.predictions, axis=1)
        f1 = f1_score(y_te, preds, average="weighted")
        results[topic][test_topic] = f1
        print(f"Evaluation on topic {test_topic}: Weighted F1 = {f1:.4f}")


=== Phase 1: Training/Fine-tuning on topic: politics1 ===


Epoch,Training Loss,Validation Loss
1,0.115700,0.130215
2,0.099400,0.107181
3,0.103600,0.140455



Classification Report after topic politics1:
              precision    recall  f1-score   support

           0       0.94      0.95      0.95      5031
           1       0.95      0.93      0.94      4717

    accuracy                           0.94      9748
   macro avg       0.94      0.94      0.94      9748
weighted avg       0.94      0.94      0.94      9748

Confusion Matrix after topic politics1:
[[4799  232]
 [ 313 4404]]
Weighted F1-score after topic politics1: 0.9440722397757778

--- Evaluation on all datasets ---


Evaluation on topic politics1: Weighted F1 = 0.9441


Evaluation on topic politics2: Weighted F1 = 0.9416


Evaluation on topic general: Weighted F1 = 0.1588


Evaluation on topic covid: Weighted F1 = 0.4562


Evaluation on topic syria: Weighted F1 = 0.4195


Evaluation on topic islam: Weighted F1 = 0.2988


Evaluation on topic notredame: Weighted F1 = 0.3594


Evaluation on topic gossip: Weighted F1 = 0.3404

=== Phase 2: Training/Fine-tuning on topic: politics2 ===


Epoch,Training Loss,Validation Loss
1,0.102500,0.106062
2,0.145800,0.148430
3,0.127500,0.122300



Classification Report after topic politics2:
              precision    recall  f1-score   support

           0       0.93      0.96      0.95      5064
           1       0.95      0.93      0.94      4684

    accuracy                           0.94      9748
   macro avg       0.94      0.94      0.94      9748
weighted avg       0.94      0.94      0.94      9748

Confusion Matrix after topic politics2:
[[4854  210]
 [ 339 4345]]
Weighted F1-score after topic politics2: 0.9436417321758267

--- Evaluation on all datasets ---


Evaluation on topic politics1: Weighted F1 = 0.9463


Evaluation on topic politics2: Weighted F1 = 0.9436


Evaluation on topic general: Weighted F1 = 0.2479


Evaluation on topic covid: Weighted F1 = 0.6153


Evaluation on topic syria: Weighted F1 = 0.5269


Evaluation on topic islam: Weighted F1 = 0.3914


Evaluation on topic notredame: Weighted F1 = 0.4410


Evaluation on topic gossip: Weighted F1 = 0.5249

=== Phase 3: Training/Fine-tuning on topic: general ===


Epoch,Training Loss,Validation Loss
1,0.093200,0.120815
2,0.121900,0.101057
3,0.158700,0.099074



Classification Report after topic general:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      2514
           1       0.00      0.00      0.00        55

    accuracy                           0.98      2569
   macro avg       0.49      0.50      0.49      2569
weighted avg       0.96      0.98      0.97      2569

Confusion Matrix after topic general:
[[2514    0]
 [  55    0]]
Weighted F1-score after topic general: 0.9680021644592334

--- Evaluation on all datasets ---


Evaluation on topic politics1: Weighted F1 = 0.3521


Evaluation on topic politics2: Weighted F1 = 0.3564


Evaluation on topic general: Weighted F1 = 0.9680


Evaluation on topic covid: Weighted F1 = 0.3600


Evaluation on topic syria: Weighted F1 = 0.3633


Evaluation on topic islam: Weighted F1 = 0.4333


Evaluation on topic notredame: Weighted F1 = 0.4654


Evaluation on topic gossip: Weighted F1 = 0.3333

=== Phase 4: Training/Fine-tuning on topic: covid ===


Epoch,Training Loss,Validation Loss
1,0.268700,0.172807
2,0.237000,0.220322
3,0.070800,0.169563



Classification Report after topic covid:
              precision    recall  f1-score   support

           0       0.97      0.98      0.97      1106
           1       0.98      0.96      0.97      1006

    accuracy                           0.97      2112
   macro avg       0.97      0.97      0.97      2112
weighted avg       0.97      0.97      0.97      2112

Confusion Matrix after topic covid:
[[1086   20]
 [  38  968]]
Weighted F1-score after topic covid: 0.9725247610612786

--- Evaluation on all datasets ---


Evaluation on topic politics1: Weighted F1 = 0.3079


Evaluation on topic politics2: Weighted F1 = 0.3007


Evaluation on topic general: Weighted F1 = 0.0040


Evaluation on topic covid: Weighted F1 = 0.9725


Evaluation on topic syria: Weighted F1 = 0.3042


Evaluation on topic islam: Weighted F1 = 0.2422


Evaluation on topic notredame: Weighted F1 = 0.3463


Evaluation on topic gossip: Weighted F1 = 0.3333

=== Phase 5: Training/Fine-tuning on topic: syria ===


Epoch,Training Loss,Validation Loss
1,1.018800,0.694653
2,0.737000,0.690397
3,0.691100,0.687118



Classification Report after topic syria:
              precision    recall  f1-score   support

           0       0.53      0.30      0.39        89
           1       0.47      0.70      0.57        80

    accuracy                           0.49       169
   macro avg       0.50      0.50      0.48       169
weighted avg       0.50      0.49      0.47       169

Confusion Matrix after topic syria:
[[27 62]
 [24 56]]
Weighted F1-score after topic syria: 0.47089406320175553

--- Evaluation on all datasets ---


Evaluation on topic politics1: Weighted F1 = 0.4031


Evaluation on topic politics2: Weighted F1 = 0.3914


Evaluation on topic general: Weighted F1 = 0.0598


Evaluation on topic covid: Weighted F1 = 0.9414


Evaluation on topic syria: Weighted F1 = 0.4709


Evaluation on topic islam: Weighted F1 = 0.2570


Evaluation on topic notredame: Weighted F1 = 0.5675


Evaluation on topic gossip: Weighted F1 = 0.3503

=== Phase 6: Training/Fine-tuning on topic: islam ===


Epoch,Training Loss,Validation Loss
1,0.580900,0.505978
2,0.319300,0.374943
3,0.247000,0.368065



Classification Report after topic islam:
              precision    recall  f1-score   support

           0       0.95      0.89      0.92        85
           1       0.86      0.93      0.90        60

    accuracy                           0.91       145
   macro avg       0.91      0.91      0.91       145
weighted avg       0.91      0.91      0.91       145

Confusion Matrix after topic islam:
[[76  9]
 [ 4 56]]
Weighted F1-score after topic islam: 0.9107795193312435

--- Evaluation on all datasets ---


Evaluation on topic politics1: Weighted F1 = 0.6073


Evaluation on topic politics2: Weighted F1 = 0.6051


Evaluation on topic general: Weighted F1 = 0.2406


Evaluation on topic covid: Weighted F1 = 0.8520


Evaluation on topic syria: Weighted F1 = 0.5440


Evaluation on topic islam: Weighted F1 = 0.9108


Evaluation on topic notredame: Weighted F1 = 0.7393


Evaluation on topic gossip: Weighted F1 = 0.5175

=== Phase 7: Training/Fine-tuning on topic: notredame ===


Epoch,Training Loss,Validation Loss
1,No log,0.537966
2,0.695900,0.549903
3,0.495600,0.560092



Classification Report after topic notredame:
              precision    recall  f1-score   support

           0       0.85      0.88      0.86        68
           1       0.80      0.74      0.77        43

    accuracy                           0.83       111
   macro avg       0.82      0.81      0.82       111
weighted avg       0.83      0.83      0.83       111

Confusion Matrix after topic notredame:
[[60  8]
 [11 32]]
Weighted F1-score after topic notredame: 0.827582544840064

--- Evaluation on all datasets ---


Evaluation on topic politics1: Weighted F1 = 0.5549


Evaluation on topic politics2: Weighted F1 = 0.5405


Evaluation on topic general: Weighted F1 = 0.1612


Evaluation on topic covid: Weighted F1 = 0.9241


Evaluation on topic syria: Weighted F1 = 0.4432


Evaluation on topic islam: Weighted F1 = 0.8280


Evaluation on topic notredame: Weighted F1 = 0.8276


Evaluation on topic gossip: Weighted F1 = 0.4929

=== Phase 8: Training/Fine-tuning on topic: gossip ===


Epoch,Training Loss,Validation Loss
1,No log,0.695968
2,0.717800,0.694192
3,0.706700,0.693338



Classification Report after topic gossip:
              precision    recall  f1-score   support

           0       0.50      1.00      0.67        50
           1       0.00      0.00      0.00        50

    accuracy                           0.50       100
   macro avg       0.25      0.50      0.33       100
weighted avg       0.25      0.50      0.33       100

Confusion Matrix after topic gossip:
[[50  0]
 [50  0]]
Weighted F1-score after topic gossip: 0.33333333333333326

--- Evaluation on all datasets ---


Evaluation on topic politics1: Weighted F1 = 0.5406


Evaluation on topic politics2: Weighted F1 = 0.5371


Evaluation on topic general: Weighted F1 = 0.9555


Evaluation on topic covid: Weighted F1 = 0.4430


Evaluation on topic syria: Weighted F1 = 0.3633


Evaluation on topic islam: Weighted F1 = 0.5712


Evaluation on topic notredame: Weighted F1 = 0.4654


Evaluation on topic gossip: Weighted F1 = 0.3333


In [9]:
# ---------------
# Results summary
# ---------------

print("\n=== Results Summary ===")
for topic, res in results.items():
    print(f"\nResults after training on topic {topic}:")
    for test_topic, f1 in res.items():
        print(f"  Test on topic {test_topic}: Weighted F1 = {f1:.4f}")


=== Results Summary ===

Results after training on topic politics1:
  Test on topic politics1: Weighted F1 = 0.9441
  Test on topic politics2: Weighted F1 = 0.9416
  Test on topic general: Weighted F1 = 0.1588
  Test on topic covid: Weighted F1 = 0.4562
  Test on topic syria: Weighted F1 = 0.4195
  Test on topic islam: Weighted F1 = 0.2988
  Test on topic notredame: Weighted F1 = 0.3594
  Test on topic gossip: Weighted F1 = 0.3404

Results after training on topic politics2:
  Test on topic politics1: Weighted F1 = 0.9463
  Test on topic politics2: Weighted F1 = 0.9436
  Test on topic general: Weighted F1 = 0.2479
  Test on topic covid: Weighted F1 = 0.6153
  Test on topic syria: Weighted F1 = 0.5269
  Test on topic islam: Weighted F1 = 0.3914
  Test on topic notredame: Weighted F1 = 0.4410
  Test on topic gossip: Weighted F1 = 0.5249

Results after training on topic general:
  Test on topic politics1: Weighted F1 = 0.3521
  Test on topic politics2: Weighted F1 = 0.3564
  Test on topic

## VERSION 3: Dataset by Date

In [7]:
dataset_df = data_by_date()

for date, df in dataset_df.items():
    print(f"Date: {date}, Number of samples: {len(df)}")

# dataset_df = dict(list(dataset_df.items())[:3]) # remove last 3 datasets

print("\nSplitting datasets into train/val/test...")
datasets = {date: split_dataset(df) for date, df in dataset_df.items()} # split all datasets in train/val/test

model, tokenizer, train_args = build_model()

print("\nComputing tokenized datasets...")
datasets =  tokenize_datasets(datasets, tokenizer) # tokenize all datasets

Date: 2011-2013, Number of samples: 55
Date: 2014, Number of samples: 114
Date: 2015, Number of samples: 84
Date: 2016, Number of samples: 63018
Date: 2017, Number of samples: 16657
Date: 2019, Number of samples: 554
Date: 2020, Number of samples: 10559

Splitting datasets into train/val/test...


Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.



Computing tokenized datasets...

=== Tokenizing dataset: 2011-2013 ===


Map: 100%|██████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 700.32 examples/s]


=== Tokenizing dataset: 2014 ===



Map: 100%|█████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 1080.30 examples/s]



=== Tokenizing dataset: 2015 ===


Map: 100%|██████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 988.10 examples/s]



=== Tokenizing dataset: 2016 ===


Map: 100%|███████████████████████████████████████████████████████████| 12604/12604 [00:04<00:00, 2662.48 examples/s]



=== Tokenizing dataset: 2017 ===


Map: 100%|█████████████████████████████████████████████████████████████| 3332/3332 [00:01<00:00, 3291.79 examples/s]



=== Tokenizing dataset: 2019 ===


Map: 100%|███████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 3031.77 examples/s]



=== Tokenizing dataset: 2020 ===


Map: 100%|████████████████████████████████████████████████████████████| 2112/2112 [00:00<00:00, 11919.13 examples/s]


In [8]:
# ------------------------------
# Fine-tuning on Dataset by Date
# ------------------------------

results = {}

# sequential training
for i, (date, data) in enumerate(datasets.items()):
    print(f"\n=== Phase {i+1}: Training/Fine-tuning on date: {date} ===")
    
    X_train, y_train = data["train"]
    X_val, y_val = data["val"]
    X_test, y_test = data["test"]

    # define trainer
    trainer = Trainer(
        model=model,
        args=train_args,
        train_dataset=X_train,
        eval_dataset=X_val,
    )
    
    # fine-tune on train + val
    trainer.train()

    # evaluate on current dataset
    y_pred = trainer.predict(X_test)
    y_pred = np.argmax(y_pred.predictions, axis=1)
    print(f"\nClassification Report after date {date}:")
    print(classification_report(y_test, y_pred))
    print(f"Confusion Matrix after date {date}:")
    print(confusion_matrix(y_test, y_pred))
    print(f"Weighted F1-score after date {date}:", f1_score(y_test, y_pred, average='weighted'))

    # evaluate on all datasets
    print("\n--- Evaluation on all datasets ---")
    results[date] = {}
    for test_date, test_data in datasets.items(): # for each date
        X_te, y_te = test_data["test"]
        preds = trainer.predict(X_te)
        preds = np.argmax(preds.predictions, axis=1)
        f1 = f1_score(y_te, preds, average="weighted")
        results[date][test_date] = f1
        print(f"Evaluation on date {test_date}: Weighted F1 = {f1:.4f}")


=== Phase 1: Training/Fine-tuning on date: 2011-2013 ===


Epoch,Training Loss,Validation Loss
1,No log,0.692013
2,No log,0.690873
3,No log,0.690308



Classification Report after date 2011-2013:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.55      1.00      0.71         6

    accuracy                           0.55        11
   macro avg       0.27      0.50      0.35        11
weighted avg       0.30      0.55      0.39        11

Confusion Matrix after date 2011-2013:
[[0 5]
 [0 6]]
Weighted F1-score after date 2011-2013: 0.3850267379679144

--- Evaluation on all datasets ---


Evaluation on date 2011-2013: Weighted F1 = 0.3850


Evaluation on date 2014: Weighted F1 = 0.3095


Evaluation on date 2015: Weighted F1 = 0.3665


Evaluation on date 2016: Weighted F1 = 0.2058


Evaluation on date 2017: Weighted F1 = 0.0000


Evaluation on date 2019: Weighted F1 = 0.2163


Evaluation on date 2020: Weighted F1 = 0.3074

=== Phase 2: Training/Fine-tuning on date: 2014 ===


Epoch,Training Loss,Validation Loss
1,No log,0.691257
2,No log,0.693013
3,No log,0.692780



Classification Report after date 2014:
              precision    recall  f1-score   support

           0       0.52      1.00      0.69        12
           1       0.00      0.00      0.00        11

    accuracy                           0.52        23
   macro avg       0.26      0.50      0.34        23
weighted avg       0.27      0.52      0.36        23

Confusion Matrix after date 2014:
[[12  0]
 [11  0]]
Weighted F1-score after date 2014: 0.35776397515527947

--- Evaluation on all datasets ---


Evaluation on date 2011-2013: Weighted F1 = 0.2841


Evaluation on date 2014: Weighted F1 = 0.3578


Evaluation on date 2015: Weighted F1 = 0.3012


Evaluation on date 2016: Weighted F1 = 0.4797


Evaluation on date 2017: Weighted F1 = 0.9934


Evaluation on date 2019: Weighted F1 = 0.4654


Evaluation on date 2020: Weighted F1 = 0.3600

=== Phase 3: Training/Fine-tuning on date: 2015 ===


Epoch,Training Loss,Validation Loss
1,No log,0.688260
2,No log,0.687809
3,No log,0.689738



Classification Report after date 2015:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         8
           1       0.53      1.00      0.69         9

    accuracy                           0.53        17
   macro avg       0.26      0.50      0.35        17
weighted avg       0.28      0.53      0.37        17

Confusion Matrix after date 2015:
[[0 8]
 [0 9]]
Weighted F1-score after date 2015: 0.36651583710407243

--- Evaluation on all datasets ---


Evaluation on date 2011-2013: Weighted F1 = 0.3850


Evaluation on date 2014: Weighted F1 = 0.3095


Evaluation on date 2015: Weighted F1 = 0.3665


Evaluation on date 2016: Weighted F1 = 0.2058


Evaluation on date 2017: Weighted F1 = 0.0000


Evaluation on date 2019: Weighted F1 = 0.2163


Evaluation on date 2020: Weighted F1 = 0.3074

=== Phase 4: Training/Fine-tuning on date: 2016 ===


Epoch,Training Loss,Validation Loss
1,0.074900,0.055451
2,0.013300,0.055869
3,0.054800,0.059183



Classification Report after date 2016:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7861
           1       0.99      0.98      0.98      4743

    accuracy                           0.99     12604
   macro avg       0.99      0.99      0.99     12604
weighted avg       0.99      0.99      0.99     12604

Confusion Matrix after date 2016:
[[7801   60]
 [  93 4650]]
Weighted F1-score after date 2016: 0.987852521165446

--- Evaluation on all datasets ---


Evaluation on date 2011-2013: Weighted F1 = 0.3636


Evaluation on date 2014: Weighted F1 = 0.4953


Evaluation on date 2015: Weighted F1 = 0.4759


Evaluation on date 2016: Weighted F1 = 0.9879


Evaluation on date 2017: Weighted F1 = 0.9943


Evaluation on date 2019: Weighted F1 = 0.3129


Evaluation on date 2020: Weighted F1 = 0.4182

=== Phase 5: Training/Fine-tuning on date: 2017 ===


Epoch,Training Loss,Validation Loss
1,0.019200,0.019730
2,0.007700,0.014994
3,0.010600,0.017730



Classification Report after date 2017:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3318
           1       0.57      0.57      0.57        14

    accuracy                           1.00      3332
   macro avg       0.78      0.78      0.78      3332
weighted avg       1.00      1.00      1.00      3332

Confusion Matrix after date 2017:
[[3312    6]
 [   6    8]]
Weighted F1-score after date 2017: 0.9963985594237695

--- Evaluation on all datasets ---


Evaluation on date 2011-2013: Weighted F1 = 0.2606


Evaluation on date 2014: Weighted F1 = 0.6522


Evaluation on date 2015: Weighted F1 = 0.5193


Evaluation on date 2016: Weighted F1 = 0.9862


Evaluation on date 2017: Weighted F1 = 0.9964


Evaluation on date 2019: Weighted F1 = 0.3437


Evaluation on date 2020: Weighted F1 = 0.4657

=== Phase 6: Training/Fine-tuning on date: 2019 ===


Epoch,Training Loss,Validation Loss
1,No log,0.693499
2,0.721100,0.744447
3,0.658300,0.763098



Classification Report after date 2019:
              precision    recall  f1-score   support

           0       0.62      0.90      0.73        68
           1       0.46      0.14      0.21        43

    accuracy                           0.60       111
   macro avg       0.54      0.52      0.47       111
weighted avg       0.56      0.60      0.53       111

Confusion Matrix after date 2019:
[[61  7]
 [37  6]]
Weighted F1-score after date 2019: 0.5332449489075995

--- Evaluation on all datasets ---


Evaluation on date 2011-2013: Weighted F1 = 0.2841


Evaluation on date 2014: Weighted F1 = 0.3578


Evaluation on date 2015: Weighted F1 = 0.3012


Evaluation on date 2016: Weighted F1 = 0.9790


Evaluation on date 2017: Weighted F1 = 0.9951


Evaluation on date 2019: Weighted F1 = 0.5332


Evaluation on date 2020: Weighted F1 = 0.5040

=== Phase 7: Training/Fine-tuning on date: 2020 ===


Epoch,Training Loss,Validation Loss
1,0.167600,0.209950
2,0.150800,0.160210
3,0.042500,0.114699



Classification Report after date 2020:
              precision    recall  f1-score   support

           0       0.97      0.98      0.98      1106
           1       0.98      0.97      0.97      1006

    accuracy                           0.98      2112
   macro avg       0.98      0.97      0.98      2112
weighted avg       0.98      0.98      0.98      2112

Confusion Matrix after date 2020:
[[1088   18]
 [  34  972]]
Weighted F1-score after date 2020: 0.975368512172596

--- Evaluation on all datasets ---


Evaluation on date 2011-2013: Weighted F1 = 0.3409


Evaluation on date 2014: Weighted F1 = 0.3734


Evaluation on date 2015: Weighted F1 = 0.4858


Evaluation on date 2016: Weighted F1 = 0.3143


Evaluation on date 2017: Weighted F1 = 0.2222


Evaluation on date 2019: Weighted F1 = 0.6029


Evaluation on date 2020: Weighted F1 = 0.9754


In [9]:
# ---------------
# Results summary
# ---------------

print("\n=== Results Summary ===")
for date, res in results.items():
    print(f"\nResults after training on date {date}:")
    for test_date, f1 in res.items():
        print(f"  Test on date {test_date}: Weighted F1 = {f1:.4f}")


=== Results Summary ===

Results after training on date 2011-2013:
  Test on date 2011-2013: Weighted F1 = 0.3850
  Test on date 2014: Weighted F1 = 0.3095
  Test on date 2015: Weighted F1 = 0.3665
  Test on date 2016: Weighted F1 = 0.2058
  Test on date 2017: Weighted F1 = 0.0000
  Test on date 2019: Weighted F1 = 0.2163
  Test on date 2020: Weighted F1 = 0.3074

Results after training on date 2014:
  Test on date 2011-2013: Weighted F1 = 0.2841
  Test on date 2014: Weighted F1 = 0.3578
  Test on date 2015: Weighted F1 = 0.3012
  Test on date 2016: Weighted F1 = 0.4797
  Test on date 2017: Weighted F1 = 0.9934
  Test on date 2019: Weighted F1 = 0.4654
  Test on date 2020: Weighted F1 = 0.3600

Results after training on date 2015:
  Test on date 2011-2013: Weighted F1 = 0.3850
  Test on date 2014: Weighted F1 = 0.3095
  Test on date 2015: Weighted F1 = 0.3665
  Test on date 2016: Weighted F1 = 0.2058
  Test on date 2017: Weighted F1 = 0.0000
  Test on date 2019: Weighted F1 = 0.2163
 